version: '2'

services:
  redis:
    restart: always
    image: taos/redis:latest
    command:
    - --loglevel warning
    networks:
      - taos-backend

  postgresql:
    restart: always
    image: taos/postgresql:gitlab
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    networks:
      - taos-backend

  gitlab:
    restart: always
    image: taos/gitlab:wrongtag
    depends_on:
    - redis
    - postgresql
    ports:
    - "80:80"
    - "10022:22"
    env_file: conf.env
    networks:
      - taos-frontend

networks:
  taos-backend:
    driver: bridge
  taos-frontend:
    driver: bridge
